### ISSUE TITLE
Update test-suite for new model architecture. 

### ISSUE THREAD

**Issue by bmcguirk** [401ode/projects#11]
This is the output of `python manage.py test --nomigrations`: 

``` bash
(venv)brianmcguirk:~/workspace/projects (master) $ python manage.py test --nomigrations
Creating test database for alias 'default'...
.EEEEEE.....s
======================================================================
ERROR: test_many_tock_ids_can_be_null (projects.tests.test_projects.ProjectModelTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/workspace/projects/projects/tests/test_projects.py", line 15, in test_many_tock_ids_can_be_null
    Project(tock_id=None).save()
  File "/home/ubuntu/workspace/projects/venv/lib/python3.5/site-packages/django/db/models/base.py", line 451, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'tock_id' is an invalid keyword argument for this function

======================================================================
ERROR: test_tock_ids_are_unique (projects.tests.test_projects.ProjectModelTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/workspace/projects/projects/tests/test_projects.py", line 9, in test_tock_ids_are_unique
    Project(tock_id=1).save()
  File "/home/ubuntu/workspace/projects/venv/lib/python3.5/site-packages/django/db/models/base.py", line 451, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'tock_id' is an invalid keyword argument for this function

======================================================================
ERROR: test_basic_search (projects.tests.test_projects.ProjectSearchTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/workspace/projects/projects/tests/test_projects.py", line 21, in setUp
    Project(tock_id=1, name="foo bar").save()
  File "/home/ubuntu/workspace/projects/venv/lib/python3.5/site-packages/django/db/models/base.py", line 451, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'tock_id' is an invalid keyword argument for this function

======================================================================
ERROR: test_case_insensitivity (projects.tests.test_projects.ProjectSearchTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/workspace/projects/projects/tests/test_projects.py", line 21, in setUp
    Project(tock_id=1, name="foo bar").save()
  File "/home/ubuntu/workspace/projects/venv/lib/python3.5/site-packages/django/db/models/base.py", line 451, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'tock_id' is an invalid keyword argument for this function

======================================================================
ERROR: test_no_results (projects.tests.test_projects.ProjectSearchTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/workspace/projects/projects/tests/test_projects.py", line 21, in setUp
    Project(tock_id=1, name="foo bar").save()
  File "/home/ubuntu/workspace/projects/venv/lib/python3.5/site-packages/django/db/models/base.py", line 451, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'tock_id' is an invalid keyword argument for this function

======================================================================
ERROR: test_query_in_tagline (projects.tests.test_projects.ProjectSearchTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/workspace/projects/projects/tests/test_projects.py", line 21, in setUp
    Project(tock_id=1, name="foo bar").save()
  File "/home/ubuntu/workspace/projects/venv/lib/python3.5/site-packages/django/db/models/base.py", line 451, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'tock_id' is an invalid keyword argument for this function

----------------------------------------------------------------------
Ran 13 tests in 0.632s

FAILED (errors=6, skipped=1)
Destroying test database for alias 'default'...
```

Impacts ability of Travis builds (see Issue #7 ) to pass.

**Comment by bmcguirk** [comment]
Updated enough to probably pass travis. Will be tracked in #12. Will close on successful travis pass.

**Comment by bmcguirk** [comment]
Closed with https://travis-ci.org/401ode/projects/builds/163814002
